### ISSUE TITLE
感觉侵入有点强。考虑下修改root layout，增加顶部Padding呢？

### ISSUE THREAD

**Issue by lsjwzh** [fython/MaterialStatusBarCompat#1]
感觉侵入有点强。考虑下修改root layout，增加顶部Padding呢？

**Comment by fython** [comment]
小弟水平有限，不太明白你的意思……
不过侵入性强确实有一点，不过对于会用 `android.support.v7.widget.Toolbar` 的开发者来说影响应该也不算很大吧。

**Comment by lsjwzh** [comment]
额。就是直接获取到layout的根元素，然后修改它的padding。但是如果要定义颜色还得像SystemBarTint一样插入一个View进去。感觉总有点不完美。有点纠结。。仅供瞎探讨一下。。。

**Comment by fython** [comment]
如果想做 Parallax App Bar 顶栏图片延伸到状态栏的可能给 root layout 加 padding 不太合适，既然现在 ActionBar 也要独立成一个控件摆放在 layout 中，加多一个控件也不会太麻烦ww

**Comment by lsjwzh** [comment]
恩呢。。主要是历史项目。。。。改起来烦躁。。。最后还是手工改了好几十个layout。。。。。。
